modules: singularity/2.2.1
container: 00script/rnaseq.img
wrapper:: rnaseq
samples:
  ERR458502:
    gt: SNF2
    rep: 1
  ERR458509:
    gt: SNF2
    rep: 2
  ERR458516:
    gt: SNF2
    rep: 3
  ERR458495:
    gt: WT
    rep: 1
  ERR458880:
    gt: WT
    rep: 2
  ERR458887:
    gt: WT
    rep: 3
reference:
  ensembl_ver: 88
  genome_build: R64-1-1
  hisat_index: 00ref/hisat_index/R64-1-1
  genome_file: 00ref/R64-1-1.fa
  cdna_file: 00ref/R64-1-1.cdna_nc.fa
